correct some typos
AlbrechtL/welle.io pull request #642
Opened 2021-03-01 07:24 UTC by tenzap

2021-03-01 07:53 UTC, gvanem commented
I believe **ADC overload** is the correct term.

2021-03-01 08:16 UTC, tenzap commented
Oh, really ? Actually I was wondering. What does ADC stand for ?

2021-03-01 09:05 UTC, gvanem commented
> What does ADC stand for ?

*Analogue to Digital Converter*; the basis of all SDRs. 
Lots of info here: https://www.rtl-sdr.com/tag/overload/

2021-03-03 20:03 UTC, marcusmueller requested changes

2021-03-03 20:03 UTC, marcusmueller commented on src/input/rtl_tcp.cpp
> +                std::string text = QT_TRANSLATE_NOOP("CRadioController", "ADC overload. Maybe you are using a too high gain.");
Even if this just seems to undo consistent line breaking (which I'd argue is undesirable in absence of an unambiguous guideline): 

This seems unidiomatic. I believe a native user would say

"Your gain might be [set] too high."

So, if you change this line, then please make it sound more "round".

2021-03-03 20:03 UTC, marcusmueller commented on src/welle-gui/QML/settingpages/RTLSDRSettings.qml
> +        text: qsTr("Enable bias tee (not supported by all dongles)")
End sentence in "."

2021-03-03 20:03 UTC, marcusmueller commented on src/welle-gui/android_rtl_sdr.cpp
> +    QAndroidJniObject message = QAndroidJniObject::fromString(QT_TR_NOOP("Android RTL-SDR driver is not installed. Would you like to install it? After install start welle.io again."));
```
- after install
+ after installation
```

2021-03-09 14:50 UTC, tenzap commented on src/welle-gui/android_rtl_sdr.cpp
> +    QAndroidJniObject message = QAndroidJniObject::fromString(QT_TR_NOOP("Android RTL-SDR driver is not installed. Would you like to install it? After install start welle.io again."));
changed

2021-04-07 16:54 UTC, marcusmueller commented on src/welle-gui/QML/settingpages/RTLSDRSettings.qml
> +        text: qsTr("Enable bias tee (not supported by all dongles)")
good point, I guess not. But seeing the position of said button, the text seems to be too long (not your fault).

2021-04-11 20:18 UTC, AlbrechtL approved these changes

2021-04-11 20:18 UTC, merged