add manpages for welle-io & welle-cli
AlbrechtL/welle.io pull request #689
Opened 2021-11-21 17:00 UTC by tenzap

2021-12-02 20:38 UTC, herrhotzenplotz reviewed
Just something that jumped into my eye.

2021-12-02 20:38 UTC, herrhotzenplotz commented on src/welle-cli/doc/man/update_manpage.sh
> +#!/bin/bash
Nit: Unportable. Use `/bin/sh` instead.

2021-12-02 20:38 UTC, herrhotzenplotz commented on src/welle-gui/doc/man/update_manpage.sh
> +#!/bin/bash
Same as above. This is unportable. Use `/bin/sh`instead.

2022-01-06 21:54 UTC, AlbrechtL requested changes
@herrhotzenplotz Thanks for checking!

@tenzap Please update the update scripts like @herrhotzenplotz recommended

2022-01-21 09:42 UTC, alexmyczko approved these changes

2022-01-21 09:42 UTC, alexmyczko commented
i had prepared manpages i forgot to send: https://sources.debian.org/src/welle.io/2.2-1/debian/

2022-02-09 22:35 UTC, AlbrechtL commented
@alexmyczko Stupid question: Do have I something to do with your man pages? As far as I see this PR includes man pages.

2022-02-10 05:59 UTC, alexmyczko commented
@AlbrechtL no, unless you feel like comparing the PR ones with the ones i have, and taking the best parts for the final version... but you can absolutely skip this step

2022-02-10 20:28 UTC, merged