Append theme path from resources
AlbrechtL/welle.io pull request #723
Opened 2022-03-11 19:16 UTC by dforsi

Fixes issue #713.

Appending would allow local icons to take precedence over those bundled.

Calling `QIcon::setThemeSearchPaths(themePaths);` replaces the whole list of paths which results in missing icons on some systems.
Adding `qDebug() << QIcon::themeSearchPaths();` before and after the call to `setThemeSearchPaths()` before this patch:
```
2022-03-11T20:12:10.344 Debug: ("/home/user/.local/share/icons", "/usr/share/icons", "/var/lib/snapd/desktop/icons", ":/icons")
2022-03-11T20:12:10.344 Debug: (":/icons/welle_io_icons")
```
after this patch:
```
2022-03-11T20:14:59.384 Debug: ("/home/user/.local/share/icons", "/usr/share/icons", "/var/lib/snapd/desktop/icons", ":/icons")
2022-03-11T20:14:59.384 Debug: ("/home/user/.local/share/icons", "/usr/share/icons", "/var/lib/snapd/desktop/icons", ":/icons", ":/icons/welle_io_icons")
```
and all the icons are visible for me.

2022-03-12 21:55 UTC, AlbrechtL requested changes
Please change to the next branch.

2022-07-05 12:13 UTC, tenzap commented
any news on this please ?

2022-08-21 11:11 UTC, AlbrechtL approved these changes

2022-08-21 11:12 UTC, AlbrechtL commented
Thanks for this fix!

2022-08-21 11:12 UTC, merged